### ISSUE TITLE
PEP 541 - Is this project abandoned?

### ISSUE THREAD

**Issue by Zeitsperre** [OpenHydrology/lmoments3#15]
Hi,

I'm trying to reach out and see if this project still has an active maintainer. A PR that my colleague and I have been trying to merge for a few months now (#13) still has not been recognized, and there doesn't seem to have been any new commits in more than 1.5 years. The last release on PyPI was in 2015.

If this is the case, I would like to ask for maintainer access or for the PyPI namespace in order to maintain an active fork of this project so that users can continue to use this package. I will attempt to reach out to the listed maintainers via email in the coming days.

If I don't hear anything back, I will begin the process of requesting the namespace from PyPI in order to maintain a fork.

All the best,

**Comment by aulemahal** [comment]
@neilnutt @faph
Who seems to have been the only ones committing to the main branches.

**Comment by faph** [comment]
Hi @Zeitsperre @aulemahal 

I don't have access to the Open Hydrology GitHub org anymore. But it seems the PyPI upload was done against my personal account.

If @neilnutt wants to accept PyPI ownership, that would be fine. If not, I am happy to assign ownership to @Zeitsperre .

**Comment by faph** [comment]
@Zeitsperre let me know the PyPI username I should assign ownership to.

**Comment by Zeitsperre** [comment]
Awesome! My username is the same as on GitHub (https://pypi.org/user/Zeitsperre/). If you require my email address, it can be found here: https://github.com/Ouranosinc/xclim/blob/master/AUTHORS.rst

**Comment by faph** [comment]
Invite sent from PyPI @Zeitsperre

**Comment by Zeitsperre** [comment]
Invitation accepted. Thanks so much for your help with this, @faph! Would you like to maintain write access to the fork (https://github.com/Ouranosinc/lmoments3/tree/develop)?

My colleague @aulemahal will be discussing the next version to be released in the coming days.

**Comment by faph** [comment]
No problem at all. Nice to see this continued elsewhere. I am no longer active in this space.
